// src/modules/shared/common/constants/events.constants.ts
export const EVENTS = {
  USER: {
    CREATE: 'USER.CREATE',
    UPDATE: 'USER.UPDATE',
    DELETE: 'USER.DELETE',
    STATUS_CHANGE: 'USER.STATUS_CHANGE',
    APPROVE: 'USER.APPROVE',
    REJECT: 'USER.REJECT',
  },
  TRIP: {
    CREATE: 'TRIP.CREATE',
    CONFIRM: 'TRIP.CONFIRM',
    UPDATE: 'TRIP.UPDATE',
    DELETE: 'TRIP.DELETE',
    STATUS_CHANGE: 'TRIP.STATUS_CHANGE',
    APPROVE: 'TRIP.APPROVE',
    REJECT: 'TRIP.REJECT',
    START: 'TRIP.START',
    FINISH: 'TRIP.FINISH',
    COMPLETE: 'TRIP.COMPLETE',
    CANCEL: 'TRIP.CANCEL',
    STARTREAD: 'TRIP.STARTREAD',
  },
  VEHICLE: {
    CREATE: 'VEHICLE.CREATE',
    UPDATE: 'VEHICLE.UPDATE',
    DELETE: 'VEHICLE.DELETE',
    ASSIGN: 'VEHICLE.ASSIGN',
    UNASSIGN: 'VEHICLE.UNASSIGN',
    STATUS_CHANGE: 'VEHICLE.STATUS_CHANGE',
  },
  NOTIFICATION: {
    CREATE: 'NOTIFICATION.CREATE',
    READ: 'NOTIFICATION.READ',
    READ_ALL: 'NOTIFICATION.READ_ALL',
    DELETE: 'NOTIFICATION.DELETE',
  },
} as const;